language: node_js
node_js: stable

cache:
  directories:
    - node_modules

branches:
  only:
  - hexo

install:
  - npm install

script:
  - hexo g

after_success:
  - cd ./public
  - git init
  - git config user.name "travis"
  - git config user.email "travis"
  - git add .
  - git commit -m "`date +%c` deploy by Travis"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master
# E: Build LifeCycle

env:
 global:
   - GH_REF: github.com/johnsoncheg/johnsoncheg.github.io.git